permission_list = [
    {"id": 1, "title": "获取所有用户", "url": "/api/admin/user", "method": "GET", "code": "system:get-all-user"},
    {"id": 2, "title": "创建单个用户", "url": "/api/admin/user", "method": "POST", "code": "system:create-one-user"},
    {"id": 3, "title": "删除多个用户", "url": "/api/admin/user", "method": "DELETE", "code": "system:delete-many-user"},
    {"id": 4, "title": "获取单个用户", "url": r"/api/admin/user/\d+", "method": "GET", "code": "system:get-one-user"},
    {"id": 5, "title": "更新单个用户", "url": r"/api/admin/user/\d+", "method": "PUT", "code": "system:update-one-user"},
    {"id": 6, "title": "删除单个用户", "url": r"/api/admin/user/\d+", "method": "DELETE", "code": "system:delete-one-user"},
    {"id": 7, "title": "获取所有角色", "url": "/api/admin/role", "method": "GET", "code": "system:get-all-role"},
    {"id": 8, "title": "创建单个角色", "url": "/api/admin/role", "method": "POST", "code": "system:create-one-role"},
    {"id": 9, "title": "删除多个角色", "url": "/api/admin/role", "method": "DELETE", "code": "system:delete-many-role"},
    {"id": 10, "title": "获取单个角色", "url": r"/api/admin/role/\d+", "method": "GET", "code": "system:get-one-role"},
    {"id": 11, "title": "更新单个角色", "url": r"/api/admin/role/\d+", "method": "PUT", "code": "system:update-one-role"},
    {"id": 12, "title": "删除单个角色", "url": r"/api/admin/role/\d+", "method": "DELETE", "code": "system:delete-one-role"},
    {"id": 13, "title": "获取所有菜单", "url": r"/api/admin/menu", "method": "GET", "code": "system:get-all-menu"},
    {"id": 14, "title": "创建单个菜单", "url": r"/api/admin/menu", "method": "POST", "code": "system:create-one-menu"},
    {"id": 15, "title": "删除多个菜单", "url": r"/api/admin/menu", "method": "DELETE", "code": "system:delete-many-menu"},
    {"id": 16, "title": "获取单个菜单", "url": r"/api/admin/menu/\d+", "method": "GET", "code": "system:get-one-menu"},
    {"id": 17, "title": "更新单个菜单", "url": r"/api/admin/menu/\d+", "method": "PUT", "code": "system:update-one-menu"},
    {"id": 18, "title": "删除单个菜单", "url": r"/api/admin/menu/\d+", "method": "DELETE", "code": "system:delete-one-menu"},
    {"id": 19, "title": "获取所有权限", "url": r"/api/admin/permission", "method": "GET", "code": "system:get-all-permission"},
    # {"id": 20, "title": "创建单个权限", "url": r"/api/admin/permission", "method": "POST", "code": "system:create-one-permission"},
    # {"id": 21, "title": "删除多个权限", "url": r"/api/admin/permission", "method": "DELETE", "code": "system:delete-many-permission"},
    {"id": 22, "title": "获取单个权限", "url": r"/api/admin/permission/\d+", "method": "GET", "code": "system:get-one-permission"},
    # {"id": 23, "title": "更新单个权限", "url": r"/api/admin/permission/\d+", "method": "PUT", "code": "system:update-one-permission"},
    # {"id": 24, "title": "删除单个权限", "url": r"/api/admin/permission/\d+", "method": "DELETE", "code": "system:delete-one-permission"},

    {"id": 25, "title": "获取所有系统日志", "url": r"/api/admin/operation_record", "method": "GET", "code": "system:get-all-operation_record"},
    {"id": 26, "title": "获取单个系统日志", "url": r"/api/admin/operation_record/\d+", "method": "GET", "code": "system:get-one-operation_record"},
]
